services:
  app:
    container_name: ${APP_NAME}_app
    build:
      context: .
    ports:
      - ${APP_EXTERNAL_PORT}:${APP_PORT}
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: ${APP_NAME}_mysql
    image: mysql:8
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 5s
      retries: 2
