services:
  app:
    container_name: ${APP_NAME}_app
    build:
      context: .
    ports:
      - ${APP_EXTERNAL_PORT}:${APP_PORT}
    volumes:
      - .:/go/src/app
  db:
    container_name: ${APP_NAME}_mysql
    image: mysql:8
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
